apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Service Port
      targetPort: 80  # Container Port
      nodePort: 30000 # Exposed Port on Node (30000-32767)
